config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do
    member do
      get :publish
    end
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_many :comments
  validates :title, presence: true
  validates :body, presence: true, length: {minimum: 10}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_id, only: [:edit, :publish, :destroy, :update]
  skip_before_action :authenticate_user!, only: [:index]

  def index
    if user_signed_in?
      @posts = Post.all
    else
      @posts = Post.where(ispublished: true)
    end
  end

  def show
    @post = Post.friendly.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def publish
    @post.update(ispublished: !@post.ispublished)
    redirect_to post_path(@post)
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def find_id
    return unless user_signed_in?

    @post = Post.find_by(slug: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_status(post)
    post.ispublished ? 'Unpublish' : 'Publish'
  end
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @post, @post.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MicroBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post do |post| %>
  <div>
    <%= post.label :title %><br>
    <%= post.text_field :title %>
  </div>

  <div>
    <%= post.label :body %><br>
    <%= post.text_area :body %><br>

  </div>

  <div>
    <%= post.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1> Edit Post </h1>
<%= render "form", post: @post %>

app/views/posts/index.html.erb
<h1>This is my Blog</h1>
<% if !user_signed_in? %>
<%= link_to "Sign In", new_user_session_path %>

<% else %>
<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
<% end %>
<ul>
  <% @posts.each do |post| %>
  <li>
    <div class="blog">
      <% if user_signed_in? %>
      <%= link_to post.title, post %>
      <% else %>
      <%= post.title %>
      <% end %>
      <br> 
      <span> Body :  </span>
      <%= post.body%> <br>
      <span>Publish Status :  </span>
      <%= post.ispublished %>
      
    <br>
  </li>
  <br>
  <% end %>
</ul>
<% if user_signed_in? %>
<button>
<%= link_to "New Post", new_post_path %>
</button>
<% end %>

app/views/posts/new.html.erb
<h1> New Post </h1>
<%= render "form", post: @post %>
<% @post.ispublished = false %>

app/views/posts/show.html.erb
<h1> This is <%= @post.id %> Blog</h1>
    <%= @post.title %> 
    <br> 
    <span> Body :  </span>
    <%= @post.body %>
    <br> <br>

<button style="padding: 5px 15px;"> 
  <%= link_to "Edit", edit_post_path(@post) %></li>
</button>



<button style="padding: 5px 15px;"> 
  <%= link_to "Delete", post_path(@post), method: :delete %>
</button>

<button style="padding: 5px 15px;"> 
  <%= link_to post_status(@post), publish_post_path(@post) %>
</button>

<br> <br>
<span> Go back to </span>
<%= link_to 'All Posts', posts_path %>


<h2>Comments</h2>
<%= render @post.comments %>
<br>
<h2>Add a comment:</h2>
<%= render 'comments/form' %>